# Generated by Django 2.0.7 on 2018-08-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_mingler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mingler',
            name='img_path',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
