# Generated by Django 2.0.7 on 2018-08-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20180822_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mingler',
            name='full_name',
            field=models.CharField(default='Anna', max_length=120),
        ),
    ]
