# Generated by Django 2.0.7 on 2018-08-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20180822_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mingler',
            name='my_hashtags',
            field=models.TextField(default='DDDDDDDDDDDDDD', null=True),
        ),
    ]
