# Generated by Django 2.0.7 on 2018-08-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20180822_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mingler',
            name='img_path',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='m/Users/ofirziv/Documents/GitHub/Mingling/mingling_app/static_in_env/media_roote/Users/ofirziv/Documents/GitHub/Mingling/mingling_app/static_in_env/media_rootd/Users/ofirziv/Documents/GitHub/Mingling/mingling_app/static_in_env/media_rooti/Users/ofirziv/Documents/GitHub/Mingling/mingling_app/static_in_env/media_roota/Users/ofirziv/Documents/GitHub/Mingling/mingling_app/static_in_env/media_root/'),
        ),
    ]
