# Generated by Django 2.0.7 on 2018-08-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20180822_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mingler',
            name='img_path',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='media/'),
        ),
    ]
