# Generated by Django 2.0.7 on 2018-08-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20180822_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='mingler',
            name='email',
            field=models.CharField(default='none', max_length=120),
        ),
    ]
