# Generated by Django 2.0.7 on 2018-08-28 15:09

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_mingler_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mingler',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
